In [1]:
from TCIAClient import TCIAClient
import pandas as pd

In [2]:
base_url = 'https://nbia.cancerimagingarchive.net/nbia-api/services/v4/'
client = TCIAClient(base_url)

In [3]:
collection_df = pd.DataFrame(data=client.get_json('getCollectionValues'))
collection_df.head()

                      Collection
0                        4D-Lung
1                        A091105
2                       ACNS0332
3                     ACRIN-6698
4  ACRIN-Contralateral-Breast-MR

In [4]:
series_df = pd.DataFrame(data=client.get_json('getSeries', {'Collection': 'Lung-PET-CT-Dx'}))
series_df.head()

,SeriesInstanceUID,StudyInstanceUID,Modality,ProtocolName,SeriesDate,SeriesDescription,SeriesNumber,Collection,Site,PatientID,...,LicenseURI,DataDescriptionURI,FileSize,ReleasedStatus,DateReleased,StudyDesc,StudyDate,Authorized,BodyPartExamined,ThirdPartyAnalysis
0,1.3.6.1.4.1.14519.5.2.1.6655.2359.115443980116...,1.3.6.1.4.1.14519.5.2.1.6655.2359.165244450683...,CT,5.84 POS,08-22-2008,Recon 2: 5mm,5,Lung-PET-CT-Dx,HIT,Lung_Dx-A0012,...,https://creativecommons.org/licenses/by/4.0/,https://doi.org/10.7937/TCIA.2020.NNC2-0461,18493580,Yes,06-17-2020,Chest,08-22-2008,1,NaN,NaN
1,1.3.6.1.4.1.14519.5.2.1.6655.2359.142073665012...,1.3.6.1.4.1.14519.5.2.1.6655.2359.165244450683...,CT,5.84 POS,08-22-2008,5mm,2,Lung-PET-CT-Dx,HIT,Lung_Dx-A0012,...,https://creativecommons.org/licenses/by/4.0/,https://doi.org/10.7937/TCIA.2020.NNC2-0461,19021680,Yes,06-17-2020,Chest,08-22-2008,1,NaN,NaN
2,1.3.6.1.4.1.14519.5.2.1.6655.2359.192913516459...,1.3.6.1.4.1.14519.5.2.1.6655.2359.165244450683...,CT,5.84 POS,08-22-2008,5mm,4,Lung-PET-CT-Dx,HIT,Lung_Dx-A0012,...,https://creativecommons.org/licenses/by/4.0/,https://doi.org/10.7937/TCIA.2020.NNC2-0461,18493370,Yes,06-17-2020,Chest,08-22-2008,1,NaN,NaN
3,1.3.6.1.4.1.14519.5.2.1.6655.2359.650617506468...,1.3.6.1.4.1.14519.5.2.1.6655.2359.165244450683...,CT,5.84 POS,08-22-2008,Recon 2: 5mm,3,Lung-PET-CT-Dx,HIT,Lung_Dx-A0012,...,https://creativecommons.org/licenses/by/4.0/,https://doi.org/10.7937/TCIA.2020.NNC2-0461,19021896,Yes,06-17-2020,Chest,08-22-2008,1,NaN,NaN
4,1.3.6.1.4.1.14519.5.2.1.6655.2359.204257665465...,1.3.6.1.4.1.14519.5.2.1.6655.2359.171494204612...,CT,5.84 POS,02-13-2009,5mm,3,Lung-PET-CT-Dx,HIT,Lung_Dx-A0013,...,https://creativecommons.org/licenses/by/4.0/,https://doi.org/10.7937/TCIA.2020.NNC2-0461,4226992,Yes,06-17-2020,POS,02-13-2009,1,NaN,NaN

In [5]:
patient_df = pd.DataFrame(data=client.get_json('getPatientStudy', {'Collection': 'Lung-PET-CT-Dx'}))
patient_df.head()

,StudyInstanceUID,StudyDate,StudyDescription,PatientAge,PatientID,PatientName,PatientSex,Collection,SeriesCount,Authorized
0,1.3.6.1.4.1.14519.5.2.1.6655.2359.165554066086...,04-04-2007,Chest,058Y,Lung_Dx-A0001,Lung_Dx-A0001,M,Lung-PET-CT-Dx,2,1
1,1.3.6.1.4.1.14519.5.2.1.6655.2359.104855313699...,04-25-2007,Thorax^AThoraxRoutine (Adult),053Y,Lung_Dx-A0002,Lung_Dx-A0002,F,Lung-PET-CT-Dx,2,1
2,1.3.6.1.4.1.14519.5.2.1.6655.2359.179476503242...,07-07-2006,Thorax^AThoraxRoutine (Adult),060Y,Lung_Dx-A0003,Lung_Dx-A0003,M,Lung-PET-CT-Dx,2,1
3,1.3.6.1.4.1.14519.5.2.1.6655.2359.191296879859...,07-25-2006,Chest,060Y,Lung_Dx-A0003,Lung_Dx-A0003,M,Lung-PET-CT-Dx,2,1
4,1.3.6.1.4.1.14519.5.2.1.6655.2359.197033995568...,07-21-2006,Chest,060Y,Lung_Dx-A0003,Lung_Dx-A0003,M,Lung-PET-CT-Dx,2,1

In [6]:
test_uid = series_df.iloc[0]['SeriesInstanceUID']

In [9]:
client.get_image(test_uid, './test/test.zip', True, True)

True